ALTER TABLE "Player" ADD COLUMN "hpMax" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "Player" ADD COLUMN "lastHpRegenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "Player"
SET "hpMax" = GREATEST("hp", 20);
