ALTER TYPE "WorldActionType" ADD VALUE 'USE_ITEM';
ALTER TYPE "WorldActionType" ADD VALUE 'DROP_ITEM';
ALTER TYPE "WorldActionType" ADD VALUE 'COOK';
ALTER TYPE "WorldActionType" ADD VALUE 'LIGHT_TORCH';
ALTER TYPE "WorldActionType" ADD VALUE 'DOUSE_TORCH';
ALTER TYPE "WorldActionType" ADD VALUE 'ADD_TWIGS';
ALTER TYPE "WorldActionType" ADD VALUE 'LIGHT_CAMPFIRE';
