const assert = require("node:assert/strict");

require("ts-node/register");

const {
  alternateKeyboardLayoutInputs,
  formatAliasSuggestion,
  normalizeInput,
  parseAlias,
  suggestAliasEntries,
  suggestAliasInputs,
  suggestKeyboardLayoutAliasEntries,
} = require("../../src/input/aliases");
const { inventoryResourceKeyFromText } = require("../../src/services/inventoryUse");
const { parseStartActionPayload, parseStartActionPayloadFromText, resolveStartActionPayload } = require("../../src/input/startPayloads");
const { autoCommandModeFromText } = require("../../src/handlers/auto");
const { isDreamGateOpeningPhrase, localGateOpenAttemptText } = require("../../src/services/tutorial");
const { normalizeCreatureActionText } = require("../../src/utils/creatureActionText");
const { resourceAccusativeName } = require("../../src/utils/resourceText");
const {
  formatTeleportCoordinateCommand,
  parseTeleportCoordinateCommand,
} = require("../../src/services/adminTeleportLinks");

function assertAlias(input, expected) {
  assert.deepEqual(parseAlias(input), expected, `Unexpected alias parse for: ${input}`);
}

const closedSettlementGateText = localGateOpenAttemptText({
  name: "Зачинені ворота",
  data: { openable: false, locked: true, locks_exit_direction: "EAST" },
});
assert.match(closedSettlementGateText, /Ворота тут є/);
assert.match(closedSettlementGateText, /східний прохід/);
assert.match(closedSettlementGateText, /відкриється лише за певних умов/);

assert.equal(normalizeInput("  /Look@Chornolis_bot!!!  "), "/look");
assert.equal(normalizeInput("/sleep_tutorial"), "/sleep tutorial");
assert.equal(normalizeInput("/queue_cancel"), "/queue cancel");
assert.equal(normalizeInput("/auto_stop"), "/auto stop");
assert.equal(normalizeInput("з’їсти   ягоди."), "з'їсти ягоди");

assert.equal(parseStartActionPayload("cmd_start"), "start");
assert.equal(parseStartActionPayload("cmd_look"), "look");
assert.equal(parseStartActionPayload("cmd_examine"), "examine");
assert.equal(parseStartActionPayloadFromText("/start cmd_look"), "look");
assert.equal(parseStartActionPayloadFromText("/start@Chornolis_bot cmd_examine"), "examine");
assert.equal(parseStartActionPayloadFromText("start cmd_news"), "news");
assert.equal(parseStartActionPayloadFromText("/start"), null);
assert.equal(parseStartActionPayloadFromText("/start cmd_look extra"), null);
assert.equal(resolveStartActionPayload({ match: undefined, text: "/start cmd_examine" }), "examine");
assert.equal(resolveStartActionPayload({ match: "cmd_look", text: "/start" }), "look");

assert.equal(formatTeleportCoordinateCommand({ x: 0, y: 9, z: -13 }), "/tp_0_9__13");
assert.equal(parseTeleportCoordinateCommand("/tp_0_9__13"), "0,9,-13");
assert.equal(parseTeleportCoordinateCommand("tp__2_10_0"), "-2,10,0");
assert.equal(parseTeleportCoordinateCommand("/tp_0_9__13@Chornolis_bot"), "0,9,-13");
assert.equal(parseStartActionPayload("cmd_news"), "news");
assert.equal(parseStartActionPayload("cmd_auto"), "auto");
assert.equal(parseStartActionPayload("cmd_auto_stop"), "autoStop");
assert.equal(parseStartActionPayload("cmd_spirit"), "auto");
assert.equal(parseStartActionPayload("cmd_spirit_stop"), "autoStop");
assert.equal(parseStartActionPayload("cmd_dukh"), "auto");
assert.equal(parseStartActionPayload("cmd_dukh_stop"), "autoStop");
assert.equal(parseStartActionPayload("cmd_poklyk"), "auto");
assert.equal(parseStartActionPayload("cmd_me"), "me");
assert.equal(parseStartActionPayload("cmd_help"), "help");
assert.equal(parseStartActionPayload("cmd_rest"), "rest");
assert.equal(parseStartActionPayload("cmd_sleep"), "sleep");
assert.equal(parseStartActionPayload("cmd_track"), "track");
assert.equal(parseStartActionPayload("cmd_follow"), "follow");
assert.equal(parseStartActionPayload("cmd_unfollow"), "unfollow");
assert.equal(parseStartActionPayload("cmd_time"), "time");
assert.equal(parseStartActionPayload("cmd_calendar"), "calendar");
assert.equal(parseStartActionPayload("cmd_weather"), "weather");
assert.equal(parseStartActionPayload("cmd_inventory"), "inventory");
assert.equal(parseStartActionPayload("cmd_say"), "say");
assert.equal(parseStartActionPayload("cmd_yell"), "yell");
assert.equal(parseStartActionPayload("cmd_call_scribes"), "callScribes");
assert.equal(parseStartActionPayload("cmd_north"), "north");
assert.equal(parseStartActionPayload("cmd_n"), "north");
assert.equal(parseStartActionPayload("cmd_south"), "south");
assert.equal(parseStartActionPayload("cmd_west"), "west");
assert.equal(parseStartActionPayload("cmd_east"), "east");
assert.equal(parseStartActionPayload("cmd_up"), "up");
assert.equal(parseStartActionPayload("cmd_down"), "down");
assert.equal(parseStartActionPayload("cmd_inside"), "inside");
assert.equal(parseStartActionPayload("cmd_outside"), "outside");
assert.equal(parseStartActionPayloadFromText("/start cmd_down"), "down");
assert.equal(parseStartActionPayload("cmd_build_campfire"), "buildCampfire");
assert.equal(parseStartActionPayload("cmd_light_campfire"), "lightCampfire");
assert.equal(parseStartActionPayload("cmd_douse_campfire"), "douseCampfire");
assert.equal(parseStartActionPayload("cmd_dismantle_campfire"), "dismantleCampfire");
assert.equal(parseStartActionPayload("cmd_dismantle_totem"), "dismantleTotem");
assert.equal(parseStartActionPayload("cmd_search_honey"), "gatherHoney");
assert.equal(parseStartActionPayload("cmd_search_beeswax"), "gatherBeeswax");
assert.equal(parseStartActionPayload("cmd_gather_honey"), "gatherHoney");
assert.equal(parseStartActionPayload("cmd_gather_beeswax"), "gatherBeeswax");
assert.equal(parseStartActionPayload("cmd look"), null);
assert.equal(parseStartActionPayload("cmd_роздивитися"), null);
assert.equal(parseStartActionPayload("unknown"), null);

assertAlias("/look", { kind: "location" });
assertAlias("/glance", { kind: "glance" });
assertAlias("глянути швидко", { kind: "glance" });
assertAlias("швидко глянути", { kind: "glance" });
assertAlias("/exits", { kind: "exits" });
assertAlias("виходи", { kind: "exits" });
assertAlias("куди можна йти", { kind: "exits" });
assertAlias("див", { kind: "look-action" });
assertAlias("дивитися", { kind: "look-action" });
assertAlias("роздивитися", { kind: "look-action" });
assertAlias("/examine", { kind: "look-action" });
assertAlias("взяти в руку ніж", { kind: "equip-inventory-item", target: "ніж" });
assertAlias("equip knife", { kind: "equip-inventory-item", target: "knife" });
assertAlias("зняти з руки ніж", { kind: "unequip-inventory-item", target: "ніж" });
assertAlias("звільнити руку", { kind: "unequip-inventory-item", target: "" });

assertAlias("південь", { kind: "move", direction: "SOUTH" });
assert.equal(parseAlias("пів"), null);
assertAlias("йти на захід", { kind: "move", direction: "WEST" });
assertAlias("/n", { kind: "move", direction: "NORTH" });
assertAlias("/up", { kind: "move", direction: "UP" });
assertAlias("Вг", { kind: "move", direction: "UP" });
assertAlias("вгору", { kind: "move", direction: "UP" });
assertAlias("вверх", { kind: "move", direction: "UP" });
assertAlias("/down", { kind: "move", direction: "DOWN" });
assertAlias("Вн", { kind: "move", direction: "DOWN" });
assertAlias("вниз", { kind: "move", direction: "DOWN" });
assertAlias("вср", { kind: "move", direction: "INSIDE" });
assertAlias("/inside", { kind: "move", direction: "INSIDE" });
assertAlias("/enter", { kind: "move", direction: "INSIDE" });
assertAlias("enter bushes", { kind: "move", direction: "INSIDE" });
assertAlias("увійти в кущі", { kind: "move", direction: "INSIDE" });
assertAlias("наз", { kind: "move", direction: "OUTSIDE" });
assertAlias("назовні", { kind: "move", direction: "OUTSIDE" });
assertAlias("/leave", { kind: "session-presence", mode: "end" });
assertAlias("leave cave", { kind: "move", direction: "OUTSIDE" });
assertAlias("/afk", { kind: "session-presence", mode: "afk" });
assertAlias("afk", { kind: "session-presence", mode: "afk" });
assertAlias("/end_session", { kind: "session-presence", mode: "end" });
assertAlias("/endSession", { kind: "session-presence", mode: "end" });
assertAlias("/quit", { kind: "session-presence", mode: "end" });
assertAlias("end session", { kind: "session-presence", mode: "end" });
assertAlias("/respawn", { kind: "beginner-return" });
assertAlias("повернення", { kind: "beginner-return" });
assertAlias("повернутися до табору", { kind: "beginner-return" });
assertAlias("/call_scribes", { kind: "call-scribes" });
assertAlias("call scribes", { kind: "call-scribes" });
assertAlias("покликати писарів", { kind: "call-scribes" });
assertAlias("звернутися до писарів", { kind: "call-scribes" });
assert.equal(parseAlias("/refresh"), null);
assertAlias("/tutorialEnd", { kind: "tutorial-end" });
assertAlias("/tutorial_end", { kind: "tutorial-end" });
assertAlias("закінчити навчання", { kind: "tutorial-end" });
assertAlias("вийти з кущів", { kind: "move", direction: "OUTSIDE" });
assertAlias("/use_mushrooms", { kind: "use-item", item: "mushrooms" });
assertAlias("/gather_berries", { kind: "gather", resourceKey: "berries" });
assertAlias("/give", { kind: "give-item", item: "", target: "" });
assertAlias("/give сире м'ясо коту", { kind: "give-item", item: "raw meat", target: "cat" });
assertAlias("дати 1 сире мʼясо коту-бережнику", { kind: "give-item", item: "raw meat", target: "cat", amount: 1 });
assertAlias("дати м'яса коту", { kind: "give-item", item: "raw meat", target: "cat" });
assertAlias("дати мясо кіт", { kind: "give-item", item: "raw meat", target: "cat" });
assertAlias("дати сирого м'яса бережнику", { kind: "give-item", item: "raw meat", target: "cat" });
assertAlias("дати сирого мяса котові-бережнику", { kind: "give-item", item: "raw meat", target: "cat" });
assertAlias("give raw meat to cat", { kind: "give-item", item: "raw meat", target: "cat" });
assertAlias("/feed_raw_meat", { kind: "give-item", item: "raw meat", target: "cat", amount: 1 });
assertAlias("/feed_raw_meet", { kind: "give-item", item: "raw meat", target: "cat", amount: 1 });
assert.equal(inventoryResourceKeyFromText("сире м'ясо"), "raw_meat");
assert.equal(inventoryResourceKeyFromText("сирого м'яса"), "raw_meat");

assertAlias("хто", { kind: "who" });
assertAlias("хтоя", { kind: "me" });
assertAlias("речі", { kind: "inventory" });
assertAlias("новини", { kind: "news" });
assertAlias("час", { kind: "time" });
assertAlias("/calendar", { kind: "calendar" });
assertAlias("calendar", { kind: "calendar" });
assertAlias("календар", { kind: "calendar" });
assertAlias("дата", { kind: "calendar" });
assertAlias("місячне коло", { kind: "calendar" });
assertAlias("/weather", { kind: "weather" });
assertAlias("weather", { kind: "weather" });
assertAlias("погода", { kind: "weather" });
assertAlias("/settings", { kind: "settings" });
assertAlias("налаштування", { kind: "settings" });
assertAlias("сповіщення", { kind: "settings" });
assertAlias("повідомлення", { kind: "settings" });
assertAlias("daynotices", { kind: "daypart-notices", mode: "show" });
assertAlias("/daynotices on", { kind: "daypart-notices", mode: "on" });
assertAlias("/daynotices off", { kind: "daypart-notices", mode: "off" });
assertAlias("automessages", { kind: "auto-messages", mode: "show" });
assertAlias("/automessages on", { kind: "auto-messages", mode: "on" });
assertAlias("/automessages off", { kind: "auto-messages", mode: "off" });
assertAlias("автоповідомлення увімкнути", { kind: "auto-messages", mode: "on" });
assertAlias("авто повідомлення вимкнути", { kind: "auto-messages", mode: "off" });
assertAlias("назад", { kind: "back" });
assertAlias("сховати клавіатуру", { kind: "hide-keyboard" });

assertAlias("/cache", { kind: "beginner-cache", action: "inspect" });
assertAlias("cache", { kind: "beginner-cache", action: "inspect" });
assertAlias("/take_cache berries", { kind: "beginner-cache", action: "take", item: "berries" });
assertAlias("take from cache berries", { kind: "beginner-cache", action: "take", item: "berries" });
assertAlias("/take_cache raw meat", { kind: "beginner-cache", action: "take", item: "raw meat" });
assertAlias("/contribute_cache herbs", { kind: "beginner-cache", action: "contribute", item: "herbs" });
assertAlias("/contribute_cache смажене м'ясо", { kind: "beginner-cache", action: "contribute", item: "смажене м'ясо" });
assertAlias("/contribute_cache_all herbs", { kind: "beginner-cache", action: "contribute-all", item: "herbs" });
assertAlias("cache contribute all raw meat", { kind: "beginner-cache", action: "contribute-all", item: "raw meat" });
assertAlias("лишити весь хмиз у скрині", { kind: "beginner-cache", action: "contribute-all", item: "хмиз" });
assertAlias("залишити все смажене м'ясо в скрині", { kind: "beginner-cache", action: "contribute-all", item: "смажене м'ясо" });
assertAlias("put twigs in cache", { kind: "put-item", item: "twigs", container: "cache" });
assertAlias("put all twigs in cache", { kind: "put-item", item: "twigs", amount: "all", container: "cache" });
assertAlias("покласти весь хмиз у скриню", { kind: "put-item", item: "хмиз", amount: "all", container: "скриню" });

assertAlias("/chat", { kind: "chat" });
assertAlias("/chat 1", { kind: "chat", mode: "time", window: "1" });
assertAlias("chat all", { kind: "chat", mode: "time", window: "all" });
assertAlias("chat location 1", { kind: "chat", mode: "location", window: "1" });
assertAlias("chat character all", { kind: "chat", mode: "character", window: "all" });

assertAlias("роздивитися сліди", { kind: "track", detail: true });
assertAlias("/examine tracks", { kind: "track", detail: true });
assertAlias("/track кіт", { kind: "track", target: "кіт" });
assertAlias("track cat", { kind: "track", target: "cat" });
assertAlias("/follow_trace", { kind: "track-gate" });
assertAlias("follow trace", { kind: "track-gate" });
assertAlias("пройти за слідом", { kind: "track-gate" });
assertAlias("пролізти за слідом", { kind: "track-gate" });
assertAlias("сліди миша", { kind: "track", target: "миша" });
assertAlias("роздивитися траву", { kind: "inspect-vegetation" });
assertAlias("оцінити відновлення", { kind: "inspect-vegetation" });
assertAlias("/examine sign", { kind: "inspect-border-marker" });
assertAlias("роздивитися межовий знак", { kind: "inspect-border-marker" });
assertAlias("придивитися до знака", { kind: "inspect-border-marker" });
assertAlias("look лавка", { kind: "inspect-feature", target: "лавка", detail: "brief" });
assertAlias("look me", { kind: "inspect-feature", target: "me", detail: "brief" });
assertAlias("дивитися я", { kind: "inspect-feature", target: "я", detail: "brief" });
assertAlias("оглянути мене", { kind: "inspect-feature", target: "мене", detail: "brief" });
assertAlias("роздивитися себе", { kind: "inspect-feature", target: "себе", detail: "full" });
assertAlias("/examine лавка", { kind: "inspect-feature", target: "лавка", detail: "full" });
assertAlias("look bench", { kind: "inspect-feature", target: "bench", detail: "brief" });
assertAlias("/look Лукан", { kind: "inspect-feature", target: "лукан", detail: "brief" });
assertAlias("глянути Лукан", { kind: "inspect-feature", target: "лукан", detail: "brief" });
assertAlias("дивитися Лукан", { kind: "inspect-feature", target: "лукан", detail: "brief" });
assertAlias("озирнутися на Лукана", { kind: "inspect-feature", target: "лукана", detail: "brief" });
assertAlias("оглянути браму", { kind: "inspect-feature", target: "браму", detail: "brief" });
assertAlias("огл брама", { kind: "inspect-feature", target: "брама", detail: "brief" });
assertAlias("придивитися до брами", { kind: "inspect-feature", target: "брами", detail: "full" });

assertAlias("збирати ягоди", { kind: "gather", resourceKey: "berries" });
assertAlias("збирати гриби", { kind: "gather", resourceKey: "mushrooms" });
assertAlias("збирати лікарські трави", { kind: "gather", resourceKey: "herbs" });
assertAlias("/search_honey", { kind: "gather", resourceKey: "honey" });
assertAlias("/search_beeswax", { kind: "gather", resourceKey: "beeswax" });
assertAlias("search honey", { kind: "gather", resourceKey: "honey" });
assertAlias("search beeswax", { kind: "gather", resourceKey: "beeswax" });
assertAlias("/gather_honey", { kind: "gather", resourceKey: "honey" });
assertAlias("/gather_beeswax", { kind: "gather", resourceKey: "beeswax" });
assertAlias("gather honey", { kind: "gather", resourceKey: "honey" });
assertAlias("gather beeswax", { kind: "gather", resourceKey: "beeswax" });
assertAlias("взяти мед", { kind: "gather", resourceKey: "honey" });
assertAlias("зібрати мед", { kind: "gather", resourceKey: "honey" });
assertAlias("обібрати вулик", { kind: "gather", resourceKey: "honey" });
assertAlias("пограбувати бортю", { kind: "gather", resourceKey: "honey" });
assertAlias("добути віск", { kind: "gather", resourceKey: "beeswax" });
assert.equal(inventoryResourceKeyFromText("мед"), "honey");
assert.equal(inventoryResourceKeyFromText("воску"), "beeswax");
assertAlias("підібрати ягоди", { kind: "pickup-target", target: "ягоди" });
assertAlias("взяти трави", { kind: "pickup-target", target: "трави" });
assertAlias("take herbs", { kind: "pickup-target", target: "herbs" });
assertAlias("get mushrooms", { kind: "pickup-target", target: "mushrooms" });
assertAlias("get all", { kind: "pickup-target", target: "all" });
assertAlias("get all corpse", { kind: "pickup-target", target: "all corpse" });
assertAlias("get all berries", { kind: "pickup-target", target: "all berries" });
assertAlias("pick all", { kind: "pickup-target", target: "all" });
assertAlias("/pick twigs", { kind: "pickup-target", target: "twigs" });
assertAlias("/pick_all", { kind: "pickup-target", target: "all" });
assertAlias("/pick_all corpse", { kind: "pickup-target", target: "all corpse" });
assertAlias("/get_all", { kind: "pickup-target", target: "all" });
assertAlias("pick_all corpse", { kind: "pickup-target", target: "all corpse" });
assertAlias("get_all", { kind: "pickup-target", target: "all" });
assertAlias("взяти все", { kind: "pickup-target", target: "все" });
assertAlias("підібрати все", { kind: "pickup-target", target: "все" });
assertAlias("підняти все", { kind: "pickup-target", target: "все" });
assertAlias("підняти всі трупи", { kind: "pickup-target", target: "всі трупи" });
assertAlias("підібрати хмиз", { kind: "pickup-target", target: "хмиз" });
assertAlias("/shake_tree", { kind: "shake-tree" });
assertAlias("потрусити дерево", { kind: "shake-tree" });
assertAlias("струсити гілки", { kind: "shake-tree" });

assertAlias("з'їсти ягоди", { kind: "use-item", item: "berries" });
assertAlias("з'їсти всі ягоди", { kind: "use-item-all", item: "berries" });
assertAlias("зʼїсти гриби", { kind: "use-item", item: "mushrooms" });
assertAlias("їсти всі гриби", { kind: "use-item-all", item: "mushrooms" });
assertAlias("використати лікарські трави", { kind: "use-item", item: "herbs" });
assertAlias("з'їсти лікарські трави", { kind: "use-item", item: "herbs" });
assertAlias("/eat_all_herbs", { kind: "use-item-all", item: "herbs" });
assertAlias("eat herbs", { kind: "use-item", item: "herbs" });
assertAlias("підсмажити м'ясо", { kind: "cook-meat" });
assertAlias("cook meat", { kind: "cook-meat" });
assertAlias("посмажити все", { kind: "cook-meat-all" });
assertAlias("/cook_all", { kind: "cook-meat-all" });
assertAlias("з'їсти м'ясо", { kind: "use-item", item: "cooked_meat" });
assertAlias("eat cooked meat", { kind: "use-item", item: "cooked_meat" });
assertAlias("eat all cooked meat", { kind: "use-item-all", item: "cooked_meat" });
assertAlias("з'їсти все смажене м'ясо", { kind: "use-item-all", item: "cooked_meat" });
assertAlias("запалити факел", { kind: "light-torch" });
assertAlias("погасити факел", { kind: "douse-torch" });
assertAlias("/build_campfire", { kind: "build-campfire" });
assertAlias("build campfire", { kind: "build-campfire" });
assertAlias("make fire", { kind: "build-campfire" });
assertAlias("скласти вогнище", { kind: "build-campfire" });
assertAlias("розкласти багаття", { kind: "build-campfire" });
assertAlias("/light_campfire", { kind: "light-campfire" });
assertAlias("light campfire", { kind: "light-campfire" });
assertAlias("підпалити вогнище", { kind: "light-campfire" });
assertAlias("/douse_campfire", { kind: "douse-campfire" });
assertAlias("put out campfire", { kind: "douse-campfire" });
assertAlias("погасити вогнище", { kind: "douse-campfire" });
assertAlias("/dismantle_campfire", { kind: "dismantle-campfire" });
assertAlias("dismantle campfire", { kind: "dismantle-campfire" });
assertAlias("розібрати вогнище", { kind: "dismantle-campfire" });
assertAlias("/dismantle_totem", { kind: "dismantle-totem" });
assertAlias("dismantle totem", { kind: "dismantle-totem" });
assertAlias("take apart totem", { kind: "dismantle-totem" });
assertAlias("розібрати тотем", { kind: "dismantle-totem" });
assertAlias("розібрати підозрілий тотем", { kind: "dismantle-totem" });
assertAlias("розв’язати тотем", { kind: "dismantle-totem" });

assertAlias("навчальний сон", { kind: "sleep", tutorial: true });
assertAlias("навчання", { kind: "sleep", tutorial: true });
assertAlias("туторіал", { kind: "sleep", tutorial: true });
assertAlias("пройти навчання", { kind: "sleep", tutorial: true });
assertAlias("повернутися до навчання", { kind: "sleep", tutorial: true });
assertAlias("/sleep_tutorial", { kind: "sleep", tutorial: true });
assertAlias("сон", { kind: "sleep" });
assertAlias("спати", { kind: "sleep" });
assertAlias("прокинутися", { kind: "wake" });
assertAlias("відкрити", { kind: "open" });
assertAlias("/open ворота", { kind: "open", target: "ворота" });
assertAlias("відкрити ворота", { kind: "open", target: "ворота" });
assertAlias("відчинити браму", { kind: "open", target: "браму" });
assertAlias("відкрий ворота", { kind: "open", target: "ворота" });
assertAlias("відч ворота", { kind: "open", target: "ворота" });
assertAlias("привідкрити двері", { kind: "open", target: "двері" });
assertAlias("o gate", { kind: "open", target: "gate" });

assertAlias("відпочити", { kind: "rest", mode: "start" });
assertAlias("додати відпочинок у чергу", { kind: "rest", mode: "queue" });
assertAlias("перервати відпочинок", { kind: "rest", mode: "interrupt" });
assertAlias("/sit", { kind: "posture", mode: "sit" });
assertAlias("сісти", { kind: "posture", mode: "sit" });
assertAlias("/lie", { kind: "posture", mode: "lie" });
assertAlias("лягти", { kind: "posture", mode: "lie" });
assertAlias("лежати", { kind: "posture", mode: "lie" });
assertAlias("/stand", { kind: "posture", mode: "stand" });
assertAlias("встати", { kind: "posture", mode: "stand" });
assertAlias("/put", { kind: "put-item", item: "туша", container: "рів" });
assertAlias("put", { kind: "put-item", item: "туша", container: "рів" });
assertAlias("покласти", { kind: "put-item", item: "туша", container: "рів" });
assertAlias("/put туша рів", { kind: "put-item", item: "туша", container: "рів" });
assertAlias("/put туша 3 падальний рів", { kind: "put-item", item: "туша", amount: 3, container: "падальний рів" });
assertAlias("/put туша all рів", { kind: "put-item", item: "туша", amount: "all", container: "рів" });
assertAlias("покласти всі рештки до ями", { kind: "put-item", item: "рештки", amount: "all", container: "ями" });
assertAlias("/put хмиз 3 скриня", { kind: "put-item", item: "хмиз", amount: 3, container: "скриня" });
assertAlias("put out torch", { kind: "douse-torch" });
assertAlias("черга", { kind: "queue", mode: "status" });
assertAlias("/queue_cancel", { kind: "queue", mode: "cancel-current" });
assertAlias("/queue_clear", { kind: "queue", mode: "clear" });
assertAlias("скасувати", { kind: "queue", mode: "cancel-current" });
assertAlias("очистити чергу", { kind: "queue", mode: "clear" });
assertAlias("/auto_stop", { kind: "auto", mode: "stop" });
assertAlias("/spirit", { kind: "auto", mode: "start" });
assertAlias("/dukh", { kind: "auto", mode: "start" });
assertAlias("/poklyk", { kind: "auto", mode: "start" });
assertAlias("поклик духа", { kind: "auto", mode: "start" });
assertAlias("покликати духа", { kind: "auto", mode: "start" });
assertAlias("дух веде", { kind: "auto", mode: "start" });
assertAlias("/spirit_stop", { kind: "auto", mode: "stop" });
assertAlias("/dukh_stop", { kind: "auto", mode: "stop" });
assertAlias("подякувати духу", { kind: "auto", mode: "stop" });
assertAlias("відпустити духа", { kind: "auto", mode: "stop" });
assertAlias("авто стоп", { kind: "auto", mode: "stop" });
assertAlias("стоп авто", { kind: "auto", mode: "stop" });
assertAlias("авто вимкнути", { kind: "auto", mode: "stop" });
assert.equal(formatAliasSuggestion(suggestAliasEntries("стоп ав")[0]), "стоп авто (/auto_stop)");
assert.equal(formatAliasSuggestion(suggestAliasEntries("авто ст")[0]), "авто стоп (/auto_stop)");
assert.equal(formatAliasSuggestion(suggestAliasEntries("вимкнути авт")[0]), "вимкнути авто (/auto_stop)");
assert.equal(autoCommandModeFromText("stop"), "stop");
assert.equal(autoCommandModeFromText("off"), "stop");
assert.equal(autoCommandModeFromText("стоп"), "stop");
assert.equal(autoCommandModeFromText("вимкнути"), "stop");
assert.equal(autoCommandModeFromText("подякувати"), "stop");
assert.equal(autoCommandModeFromText("відпустити"), "stop");
assert.equal(autoCommandModeFromText(""), "start");

assertAlias("сказати Хай стежка буде м'якою.", { kind: "say", text: "Хай стежка буде м'якою." });
assertAlias("/say Відчинитися", { kind: "say", text: "Відчинитися" });
assertAlias("Сказати «Відчинитися»", { kind: "say", text: "«Відчинитися»" });
assertAlias("Ви сказали:\nВідчинитися", { kind: "say", text: "Відчинитися" });
assertAlias("Ви сказали Відчинитися", { kind: "say", text: "Відчинитися" });
assertAlias("говорити Відчинись будь ласка", { kind: "say", text: "Відчинись будь ласка" });
assertAlias("ск Можеш відчинитися", { kind: "say", text: "Можеш відчинитися" });
assertAlias("/сказ Відчинися", { kind: "say", text: "Відчинися" });
assertAlias("гов Відкрийся", { kind: "say", text: "Відкрийся" });
assertAlias("whisper Данило Тихіше, там щось є.", { kind: "whisper", text: "Данило Тихіше, там щось є." });
assertAlias("/шепнути Велика Оля Не руш.", { kind: "whisper", text: "Велика Оля Не руш." });
assertAlias("reply Я почув.", { kind: "reply", text: "Я почув." });
assertAlias("/reply", { kind: "reply", text: "" });
assertAlias("/відповісти Йду за тобою.", { kind: "reply", text: "Йду за тобою." });
assertAlias("say", { kind: "say", text: "" });
assertAlias("сказати", { kind: "say", text: "" });
assertAlias("whisper", { kind: "whisper", text: "" });
assertAlias("шепнути", { kind: "whisper", text: "" });
assertAlias("/yell", { kind: "yell", text: "" });
assertAlias("yell", { kind: "yell", text: "" });
assertAlias("call", { kind: "yell", text: "" });
assertAlias("гукнути", { kind: "yell", text: "" });
assertAlias("покликати", { kind: "yell", text: "" });
assertAlias("крикнути поруч", { kind: "yell", text: "" });
assertAlias("/yell Сюди!", { kind: "yell", text: "Сюди!" });
assertAlias("yell Сюди!", { kind: "yell", text: "Сюди!" });
assertAlias("call Сюди!", { kind: "yell", text: "Сюди!" });
assertAlias("гукнути Хто там?", { kind: "yell", text: "Хто там?" });
assertAlias("покликати Хто там?", { kind: "yell", text: "Хто там?" });
assertAlias("крикнути поруч Стій!", { kind: "yell", text: "Стій!" });
assertAlias("гучно сказати Обережно!", { kind: "yell", text: "Обережно!" });
assertAlias("shout", { kind: "shout", text: "" });
assertAlias("вигукнути", { kind: "shout", text: "" });
assertAlias("shout Сюди!", { kind: "shout", text: "Сюди!" });
assertAlias("крикнути Стій!", { kind: "shout", text: "Стій!" });
assertAlias("кричати Допоможіть!", { kind: "shout", text: "Допоможіть!" });
assertAlias("крик Допоможіть!", { kind: "shout", text: "Допоможіть!" });
assertAlias("вигукнути Обережно!", { kind: "shout", text: "Обережно!" });
assertAlias("волати Не йдіть туди!", { kind: "shout", text: "Не йдіть туди!" });
assert.equal(isDreamGateOpeningPhrase("Відчинитися"), true);
assert.equal(isDreamGateOpeningPhrase("Відчинись будь ласка"), true);
assert.equal(isDreamGateOpeningPhrase("Можеш відчинитися?"), true);
assert.equal(isDreamGateOpeningPhrase("Сьогодні гарний туман"), false);
assertAlias("роздивитися труп", { kind: "inspect-feature", target: "труп", detail: "full" });
assertAlias("атакувати мишу", { kind: "target-action", action: "attack", target: "мишу" });
assertAlias("атака миша", { kind: "target-action", action: "attack", target: "миша" });
assertAlias("/attack mouse", { kind: "target-action", action: "attack", target: "mouse" });
assertAlias("attack_mouse", { kind: "target-action", action: "attack", target: "mouse" });
assertAlias("fight wolf", { kind: "target-action", action: "attack", target: "wolf" });
assertAlias("kick rabbit", { kind: "target-action", action: "attack", target: "rabbit" });
assertAlias("привітати 1", { kind: "target-action", action: "greet", target: "1" });
assertAlias("говорити з мандрівником", { kind: "target-action", action: "greet", target: "мандрівником" });
assertAlias("освіжити труп", { kind: "target-action", action: "freshen", target: "труп" });
assertAlias("butcher corpse", { kind: "target-action", action: "freshen", target: "corpse" });
assertAlias("розібрати труп", { kind: "target-action", action: "freshen", target: "труп" });
assertAlias("freshen all", { kind: "target-action", action: "freshen", target: "all" });
assertAlias("/freshen_all", { kind: "target-action", action: "freshen", target: "all" });
assertAlias("свіжувати все", { kind: "target-action", action: "freshen", target: "все" });
assertAlias("освіжити всі", { kind: "target-action", action: "freshen", target: "всі" });
assertAlias("викинути факел", { kind: "drop-inventory-item", target: "факел" });
assertAlias("drop all", { kind: "drop-inventory-item", target: "all" });
assertAlias("drop all corpse", { kind: "drop-inventory-item", target: "all corpse" });
assertAlias("викинути все", { kind: "drop-inventory-item", target: "все" });
assertAlias("річ ягоди", { kind: "inspect-inventory-item", target: "ягоди" });
assert.equal(inventoryResourceKeyFromText("mushroom"), "mushrooms");
assert.equal(inventoryResourceKeyFromText("raw meat"), "raw_meat");
assert.equal(inventoryResourceKeyFromText("труп лиса"), "corpse_fox_male");
assert.equal(inventoryResourceKeyFromText("труп лисиці"), "corpse_fox_female");
assert.equal(inventoryResourceKeyFromText("труп миша"), "corpse_mouse_male");
assert.equal(resourceAccusativeName({ key: "grass", name: "трава" }), "траву");
assert.equal(normalizeCreatureActionText("їсть трава"), "їсть траву");
assert.equal(normalizeCreatureActionText("підбирає факел до мисливського набору; hunter_torches:1"), "підбирає факел до мисливського набору");
assert.equal(normalizeCreatureActionText("вертається до воріт із запаленим факелом і запасним у торбі; hunter_returning_for_torches; hunter_torches:2"), "вертається до воріт із запаленим факелом і запасним у торбі");
assert.equal(normalizeCreatureActionText("claimed_by_hunter:12; мисливець несе здобич до падального рову"), "мисливець несе здобич до падального рову");
assertAlias("кивнути Здравомир", { kind: "social-signal", signal: "nod", target: "здравомир" });
assertAlias("smile", { kind: "social-signal", signal: "smile" });
assertAlias("посміх", { kind: "social-signal", signal: "smile" });
assertAlias("усміхнутися", { kind: "social-signal", signal: "smile" });
assertAlias("/follow знахар", { kind: "follow", target: "знахар" });
assertAlias("follow herbalist", { kind: "follow", target: "herbalist" });
assertAlias("слідувати за знахарем", { kind: "follow", target: "знахарем" });
assertAlias("йти за Нестором", { kind: "follow", target: "нестором" });
assertAlias("триматися за Лукана", { kind: "follow", target: "лукана" });
assertAlias("стежити за мишею", { kind: "follow", target: "мишею" });
assertAlias("/follow_assist", { kind: "follow-assist", mode: "show" });
assertAlias("/follow_assist on", { kind: "follow-assist", mode: "on" });
assertAlias("/follow_assist off", { kind: "follow-assist", mode: "off" });
assertAlias("/follow_auto", { kind: "follow-assist", mode: "show" });
assertAlias("/autofollow", { kind: "follow-assist", mode: "show" });
assertAlias("/stop_follow_assist", { kind: "follow-assist", mode: "off" });
assertAlias("йти слідом автоматично", { kind: "follow-assist", mode: "on" });
assertAlias("триматися сліду автоматично", { kind: "follow-assist", mode: "on" });
assertAlias("автослідування", { kind: "follow-assist", mode: "show" });
assertAlias("увімкнути слідування", { kind: "follow-assist", mode: "on" });
assertAlias("вимкнути слідування", { kind: "follow-assist", mode: "off" });
assertAlias("не йти слідом автоматично", { kind: "follow-assist", mode: "off" });
assertAlias("/group", { kind: "travel-group", action: "show" });
assertAlias("/travel_group", { kind: "travel-group", action: "show" });
assertAlias("гурт", { kind: "travel-group", action: "show" });
assertAlias("створити гурт", { kind: "travel-group", action: "create" });
assertAlias("запросити до гурту Орина", { kind: "travel-group", action: "invite", target: "орина" });
assertAlias("прийняти гурт", { kind: "travel-group", action: "accept" });
assertAlias("відхилити гурт", { kind: "travel-group", action: "decline" });
assertAlias("вийти з гурту", { kind: "travel-group", action: "leave" });
assertAlias("розпустити гурт", { kind: "travel-group", action: "disband" });
assertAlias("йти за провідником гурту", { kind: "travel-group", action: "follow-leader" });
assertAlias("триматися гурту", { kind: "travel-group", action: "follow-leader" });
assertAlias("/follow_step", { kind: "follow-step" });
assertAlias("/keep_following", { kind: "follow-step" });
assertAlias("/trail", { kind: "follow-step" });
assertAlias("йти слідом", { kind: "follow-step" });
assertAlias("спробувати йти слідом", { kind: "follow-step" });
assertAlias("піти слідом", { kind: "follow-step" });
assertAlias("рушити слідом", { kind: "follow-step" });
assertAlias("йти за слідом", { kind: "follow-step" });
assertAlias("триматися сліду", { kind: "follow-step" });
assertAlias("/unfollow", { kind: "unfollow" });
assertAlias("відстати", { kind: "unfollow" });
assertAlias("stop follow", { kind: "unfollow" });

assert.equal(parseAlias("це точно не команда"), null);
assert.ok(suggestAliasInputs("роздивит").includes("роздивитися"), "Expected alias suggestions to include роздивитися");
assert.ok(suggestAliasInputs("пів").includes("північ"), "Expected alias suggestions to include північ");
assert.ok(suggestAliasInputs("пів").includes("південь"), "Expected alias suggestions to include південь");
assert.ok(suggestAliasInputs("назо").includes("назовні"), "Expected alias suggestions to include назовні");
assert.ok(suggestAliasInputs("крик Допоможіть!").includes("крикнути"), "Expected alias suggestions to include крикнути");
assert.ok(suggestAliasInputs("крич").includes("кричати"), "Expected alias suggestions to include кричати");
assert.ok(suggestAliasInputs("шеп").includes("шепнути"), "Expected alias suggestions to include шепнути");
assert.ok(suggestAliasInputs("огл брама").includes("оглянути"), "Expected alias suggestions to include оглянути");
assert.ok(suggestAliasEntries("огл брама").map(formatAliasSuggestion).includes("оглянути (/examine)"), "Expected formatted suggestions to include slash command for оглянути");
assert.ok(suggestAliasEntries("швидк").map(formatAliasSuggestion).includes("швидкий огляд (/glance)"), "Expected formatted suggestions to include slash command for quick glance");
assert.ok(suggestAliasEntries("стат").map(formatAliasSuggestion).includes("статистика (/stat)"), "Expected formatted suggestions to include slash command for statistics");
assert.ok(suggestAliasEntries("гриб").map(formatAliasSuggestion).some((suggestion) => suggestion.includes("(/use_mushrooms)")), "Expected formatted suggestions to include slash command for using mushrooms");
assert.ok(suggestAliasEntries("навч").map(formatAliasSuggestion).some((suggestion) => suggestion.includes("(/sleep_tutorial)")), "Expected formatted tutorial suggestions to use clickable slash command");
assert.ok(suggestAliasEntries("повернен").map(formatAliasSuggestion).includes("повернення (/respawn)"), "Expected formatted beginner-return suggestions to use /respawn");
assert.ok(suggestAliasEntries("писар").map(formatAliasSuggestion).includes("покликати писарів (/call_scribes)"), "Expected formatted scribe-help suggestions to use /call_scribes");
assert.ok(suggestAliasEntries("закінчити нав").map(formatAliasSuggestion).includes("закінчити навчання (/tutorialEnd)"), "Expected formatted tutorial-end suggestions to use slash command");
assert.ok(suggestAliasEntries("погод").map(formatAliasSuggestion).includes("погода (/weather)"), "Expected formatted weather suggestions to include /weather");
assert.ok(suggestAliasEntries("кален").map(formatAliasSuggestion).includes("календар (/calendar)"), "Expected formatted calendar suggestions to include /calendar");
assert.ok(suggestAliasEntries("freshen al").map(formatAliasSuggestion).includes("freshen all (/freshen_all)"), "Expected formatted suggestions to include slash command for bulk freshening");
assert.ok(suggestAliasEntries("потрус").map(formatAliasSuggestion).includes("потрусити дерево (/shake_tree)"), "Expected formatted suggestions to include slash command for tree shaking");
assert.ok(suggestAliasEntries("гук").map(formatAliasSuggestion).includes("гукнути (/yell)"), "Expected formatted suggestions to include slash command for nearby yell");
assert.ok(suggestAliasEntries("гукнти").map(formatAliasSuggestion).includes("гукнути (/yell)"), "Expected formatted suggestions to include slash command for mistyped nearby yell");
assert.ok(suggestAliasEntries("вола").map(formatAliasSuggestion).includes("волати (/shout)"), "Expected formatted suggestions to keep волати as region shout");
assert.ok(suggestAliasInputs("усхмі").includes("усміх"), "Expected social suggestions to include усміх for a mistyped smile");
assert.ok(suggestAliasInputs("посмі").includes("посміх"), "Expected social suggestions to include посміх");
assert.ok(suggestAliasEntries("усхмі").map(formatAliasSuggestion).includes("усміх (/smile)"), "Expected formatted social suggestions to include slash command for smile");
assert.ok(alternateKeyboardLayoutInputs("[nj").includes("хто"), "Expected English-layout typo [nj to convert to хто");
assert.ok(suggestKeyboardLayoutAliasEntries("[nj").map(formatAliasSuggestion).includes("хто (/who)"), "Expected keyboard-layout suggestions to include /who");
assert.ok(suggestKeyboardLayoutAliasEntries("htxb").map(formatAliasSuggestion).includes("речі (/inventory)"), "Expected keyboard-layout suggestions to include inventory");

console.log("Input aliases OK");
